### ISSUE TITLE
absence the value of R

### ISSUE THREAD

**Issue by kjyjxy** [nicolasfguillaume/Recommender-Systems-Making-Movies-Recommendation#1]
Hey! Recently，I debug your program in my computer, but I have met a problem: In your program, A value named 'R' has not defined, please check out your program, thank you for your cooperation.
`df = pd.DataFrame(R).replace('0', np.nan).count(axis=1)  # count number of ratings per user
binwidth = 10
df.hist(bins=np.arange(min(df), max(df) + binwidth, binwidth))    
plt.xlabel('Number of ratings per user')
plt.ylabel('Frequency')
plt.title('Distribution of ratings count per user')`

**Comment by nicolasfguillaume** [comment]
Hi @shenyuan299319, thanks for your interest. It appears that the value of R is defined afterwards in section II, under `Defining a Rating matrix R`. However, you are correct, R should have been defined earlier in the file.
